### ISSUE TITLE
Channel is not thread safe

### ISSUE THREAD

**Issue by pnuz3n** [streadway/amqp#119]
Channel.shutdown(*error) function sets me.send function using lock. However Ack, Nack, Reject functions are not using the same lock.

Is the Channel supposed to be thread safe? Simple fix would be just add locking to those methods missing it, but I am not sure if there is something else behind this.

**Comment by michaelklishin** [comment]
This issue seems to be very broad. Discussing concurrency hazard safety without specific scenarios is going to be very time consuming at best. Most clients do not support concurrent *publishing* on a shared channel: this is not unreasonable.

If there are specific examples that are still not covered over 2 years later, please file new, more focussed issues. Thank you.
