### ISSUE TITLE
Infinite loop for consumer when rabbitmq is stopped

### ISSUE THREAD

**Issue by therahulprasad** [streadway/amqp#183]
Program: [Gist link](https://gist.github.com/therahulprasad/f5d3ca24e0197f286f58)
Important part:

```
func main() {
    conn, err := amqp.Dial("amqp://guest:guest@localhost:5672/")
    if err != nil {
        log.Fatalln(err.Error())
    }


    ch, err := conn.Channel()
    if err != nil {
        log.Fatalln(err.Error())
    }

    _, err = ch.QueueDeclare(
        "hello", // name
        true,         // durable
        false,        // delete when unused
        false,        // exclusive
        false,        // no-wait
        nil,          // arguments
    )
    consumer, err := ch.Consume("hello", "", false, false, false, false, nil)
    if err != nil {
        log.Fatalln(err.Error())
    }

    chKill := make(chan int)
    chQuit := make(chan os.Signal, 2)
    signal.Notify(chQuit, os.Interrupt, syscall.SIGTERM)

    go func() {
        for range chQuit {
            // TODO: Persist some data and then return
            fmt.Println("SigQuit \n")
            chKill<- 1
        }
    }()
    go func() {
        for {
            select {
            case d, _ := <-consumer:
                fmt.Printf("Received 1 : %s \n", d.Body)
                d.Ack(false)
            case <-chKill:
                // Do some important work before exiting
                os.Exit(0)
            }
        }
    }()

    forever := make(chan int)
    <-forever
}
```

I created a simple program to create a channel and a consumer on the channel. Then I stopped rabbitmq. I noticed that consumer started receiving blank messages on an infinite loop.

```
for {
  select {
  case d, _ := <-consumer:
  ....... 
  }
}
```

Output: 

```
Received 1 :  
Received 1 :  
Received 1 :  
Received 1 :  
Received 1 :  
...... till I pressed Ctrl+C
```

**Comment by michael-go** [comment]
Hi,

I stumbled upon your issue when I tried to understand how should I deal with rabbit connection going down.

My conclusion  is that its kinda an expected behaviour. If you check the error returned from the `d.Ack(false)` in your example, you'll see its not null.

also the `machinery` project handles the case that the Body is empty as a way to detect that the rabbit is down: https://github.com/RichardKnop/machinery/blob/9ebf06403a7e69cdd1226dd68a88ae56c5efc7a2/v1/brokers/amqp.go#L147

It actually makes sense, cause unless the consumer will receive something on the channel, how would it be notified of a dead connection.

Hope it helps,
Michael

**Comment by leea** [comment]
Hi,

I also stumbled on this too. @michael-go is right and this is working as intended. What's going on here is that the connection to rabbitmq closes so the delivery channel also closes.  According to the go spec,[ a receive on a closed channel immediately returns the zero value](https://golang.org/ref/spec#Receive_operator), in this case a Delivery with and empty body. 

Checking `ok` here:
```
  case d, ok := <-consumer:
  if !ok { ...
  ....... 
```

would show that the channel is closed.
