### ISSUE TITLE
Reliable publish messages

### ISSUE THREAD

**Issue by secmask** [streadway/amqp#201]
I'm making a small test like this [http://pastebin.com/xZ0UKX3q](http://pastebin.com/xZ0UKX3q).
Idear is, my app receive data from web service, then publish a persistent message into a durable queue.
Messages are come individual, so I cann't batch `Publish`.

I just need message confim to received by RabbitMQ server( no fsync/flush disk needed).
problem is, without confirm mode, messages seem lost. I don't want to close `Channel` to flush message because I intend to use it for long time.
In confirm mode, performance drop so much (20k req/s vs ten req/s)

So, what's the best option for me?

**Comment by michaelklishin** [comment]
Publisher confirms is the only reliable way but if you keep connection and channel open for a long time, there is no need to close them to "flush" anything. Publisher confirms don't have that much output if your client doesn't wait for every confirm. If you absolutely have to wait for every confirm, tough luck: that drastically reduces throughput by definition.

Every messaging application needs to find a balance between safety and maximum possible throughput.

**Comment by secmask** [comment]
> there is no need to close them to "flush" anything
yep, I know that, but I just don't want to lost data if client side crash.

**Comment by secmask** [comment]
without fsync, I can see that Confirm mode require one more TCP/IP round. Cann't imagine how does it make so slow.

**Comment by michaelklishin** [comment]
Confirms (`basic.ack` or `basic.nack` methods) are send by RabbitMQ entirely asynchronously. It is not a network roundtrip unless the client waits for it. Several client libraries provide two ways of using publisher confirms: block-and-wait and callbacks of some kind.

If block-and-wait is used, then every message published becomes a round trip instead of completely asynchronous publishing. And yes, that has *significant* effect on throughput. I'm not sure why you expect it to be anything else.

I'd expect this client to provide an asynchronous way of handling publisher confirms.

**Comment by secmask** [comment]
hm, asynchronous way will work good if I have a bunch of messages to publish at a time, unfortunely I received them as single one at a time. Collect messages to make batch publish will has a risk to lost messages when crash occur. Anw, look like I have to choose performance and safety.

**Comment by michaelklishin** [comment]
I'll close this because this is a question and I've outlined main options above. If this client does not support "streaming confirms" or there's a specific point of improvement for it, please file a separate issue about that.
