### ISSUE TITLE
Attempts to use a closed connection should immediately report an error

### ISSUE THREAD

**Issue by michaelklishin** [streadway/amqp#219]
Currently the error isn't too bad (see https://github.com/streadway/amqp/issues/218) but it could be even clearer. Multiple client libraries (Java, .NET, Bunny) immediately throw an `AlreadyClosedException` or similar, for example.

Note that technically this is an API change but I doubt a lot of people rely on the current behavior (or run into it in the first place). So this is arguably a usability problem that requires a tiny breaking API change.

**Comment by DmitriyMV** [comment]
Current behavior requires something like:

```go
func isErrClosedConn(err error) bool {
	if opErr, ok := err.(*net.OpError); ok && opErr.Err.Error() == "use of closed network connection" {
		return true
	}

	return false
}
```
To find verify error type. The problem here is that errClosing is non-pulic type in `net` package, which results in `==` check (which can change in future versions). 

`streadway/amqp` already contains some functionality that allows it to close only once (see `func (me *Connection) shutdown(err *Error) `. I believe it can be adjusted, so that `Close` it will result in no-op or custom error if connection is already closed.

**Comment by michaelklishin** [comment]
@DmitriyMV if you have a specific idea of how that might look like, feel free to submit a PR. @gerhard and I should have a chance to spend a few hours on this client this week.

**Comment by michaelklishin** [comment]
I believe this was addressed in master.
