### ISSUE TITLE
Publish fixed versions in gopkg.in

### ISSUE THREAD

**Issue by davisford** [streadway/amqp#255]
Would be nice if you published the lib in [gopkg.in](http://labix.org/gopkg.in) so we could fix the dependency version in projects.

**Comment by michaelklishin** [comment]
Thank you for the suggestion. Our team believes that currently it makes no sense for us to use `gopkg.in` because we are very conservative about breaking API changes. This has been going on for such a long time that the only way forward for this project under its current name is to continue doing that (we are hyperaware of the downsides of this approach).

**Comment by gerhard** [comment]
You can always trust master to work and be backwards-compatible.

Any non-backwards compatible changes will be introduced as `streadway/amqp2` most likely.
