### ISSUE TITLE
Any solution for RabbitMQ direct reply to?

### ISSUE THREAD

**Issue by jamiri** [streadway/amqp#263]
In implementing RPC using this [method](https://www.rabbitmq.com/direct-reply-to.html) RabbitMQ necessitates client to consume before publishing any message and since consuming returns a blocking channel it is not possible to publish after that. There should be non blocking way to guarantee consuming before publishing. So how can we achieve that?

**Comment by jpwilliams** [comment]
I don't think this would ever be explicitly supported by a library like this which aims more at adhering to the AMQP 0.9.1 spec rather than making common use cases easier and that's good separation.

There's a semi-complete version of [remit](https://www.npmjs.com/package/remit) in Go at [jpwilliams/go-remit](https://github.com/jpwilliams/go-remit). Not yet at 1.0.0, but if you don't use it you can look at how it achieves the req/res behaviour you're looking for.

**Comment by jamiri** [comment]
@jpwilliams  

> aims more at adhering to the AMQP 0.9.1 spec

Quite compelling. I'll have a look at go-remit pretty soon.

**Comment by michaelklishin** [comment]
Direct reply-to doesn't need any special library support. We are not against having something that makes it easier to use but projects such as go-remit is where it really belongs.
