### ISSUE TITLE
Question on docs for channel.Qos

### ISSUE THREAD

**Issue by iselind** [streadway/amqp#310]
In the docs for channel.Qos i find the following
```
When global is true, these Qos settings apply to all existing and future
consumers on all channels on the same connection.  When false, the Channel.Qos
settings will apply to all existing and future consumers on this channel.
RabbitMQ does not implement the global flag.
```
What does that last part (`RabbitMQ does not implement the global flag.`) actually mean? There is more than RabbitMQ that speak the AMQP protocol. Doesn't the `global` parameter have any effect at all if i connect to a RabbitMQ server?

**Comment by iselind** [comment]
I am also having a hard time figuring out how to revert the Qos setting. Does `channel.Qos(0,0,true)` revert all QoS settings previously made?

**Comment by lukebakken** [comment]
You can read about how RabbitMQ uses the `basic.qos` method [in this document](https://www.rabbitmq.com/consumer-prefetch.html): [link](https://www.rabbitmq.com/consumer-prefetch.html). The meaning of the `global` flag is discussed [here](https://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.qos): [link](https://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.qos).

> Does channel.Qos(0,0,true) revert all QoS settings previously made?

I suspect that it only applies to new consumers. You can set up a test scenario to confirm that.

**Comment by iselind** [comment]
The `global` flag is indeed implemented, according to the link you provided on the `global` flag, at least as i understand it. I am still not clear on what `RabbitMQ does not implement the global flag` mean.

If i do `channel.Qos(0,0,true)`, how do you come to the conclusion that it will only apply to new consumers. Your documentation state

> When global is true, these Qos settings apply to all existing and future consumers on all channels on the same connection.

`channel.Qos(0,0,true)` should, based on your documentation, mean that prefetch size and count are set to zero for all existing and future consumers on all channels on the same connection. You don't seem to agree. What am i missing?

It would help me quite a lot of you helped med clear this up.

**Comment by lukebakken** [comment]
> You don't seem to agree

I said that "I suspect" but the documentation says otherwise, like you said. I have edited my comment so as to not cause confusion.

It seems like you have a good understanding of what needs to happen. Why not try it out yourself to see what effect `channel.Qos(0, 0, true)` has?

**Comment by iselind** [comment]
Simply because I don't feel I have a good enough understanding of the
underlying functionality to see how much I need to test and more
importantly what I need to test, in order to see the whole picture.

What I see when I test might be true only in part as my test is flawed
somehow.

Patrik

Den 2 jan 2018 19:32 skrev "Luke Bakken" <notifications@github.com>:

**Comment by lukebakken** [comment]
I took the `_examples/consumer.go` code from [here](https://github.com/streadway/amqp/blob/master/_examples/simple-consumer/consumer.go) and modified it to start two consumers on the same channel ([code](https://gist.github.com/lukebakken/634e350db0ba3e9009ae4d2357652337)). You can use this code to test out different `Qos` scenarios when consumers share the same channel. Comment-out the two calls that set `Qos` per-consumer and un-comment [this code](https://gist.github.com/lukebakken/634e350db0ba3e9009ae4d2357652337#file-consumer-go-L57-L63) to see what happens when global is `true`. You can also use the RabbitMQ Management web interface to view the channels and consumers for a queue to "double check" the `Qos` setting.

I will open a PR to change the comment about RabbitMQ and the `global` flag. It should read like this:

----

Please see [the RabbitMQ Consumer Prefetch documentation](https://www.rabbitmq.com/consumer-prefetch.html) for an explanation of how the `global` flag is implemented in RabbitMQ, as it is differs from the AMQP 0.9.1 specification in that global `Qos` settings are limited in scope to channels, not connections.

**Comment by iselind** [comment]
Thank you, much appreciated. I will try the code that you suggest.
