### ISSUE TITLE
Channels are NOT thread safe for concurrent consume/publish

### ISSUE THREAD

**Issue by koliyo** [streadway/amqp#327]
From what I understand in the following issues, the library is designed for thread saftey using the same channel in multiple goroutines. 

- https://github.com/streadway/amqp/issues/208
- https://github.com/streadway/amqp/issues/119
- https://github.com/streadway/amqp/issues/318
- https://github.com/streadway/amqp/issues/77

I have found that this is not true if 

1. Consuming and publishing to the same channel
2. Auto-ack is disabled on the consumer

I do not have a small example to show, but it was resolved when I changed my setup to using separate channels for consuming and publishing.

If this kind of usage is discouraged it should really be mentioned in the documentation.

**Comment by lukebakken** [comment]
This has already been discussed in #270. It seems like an anti-pattern to use the same channel to consume and publish. Why would you do that? @michaelklishin should have more to say as well.

> I have found that this is not true

Can you elaborate? Do you get exceptions or other errors? "this is not true" is a meaningless statement.

> I do not have a small example to show

Opening an issue without code and / or instructions to reproduce the issue is not helpful. It would be appreciated if you provide code to reproduce, or at the very least, detailed steps to do so.

> If this kind of usage is discouraged it should really be mentioned in the documentation.

If this turns out to be an actual issue and not just non-optimal code, we would welcome a pull request. This library and its associated documentation are all available in this repository.

**Comment by koliyo** [comment]
Ok, thanks for reply, and sorry for not being more helpful with the report. I don't have time to investigate this further right now I'm afraid. It is working very well now that I split up the consume and publish channels.

I'm new to using AMQP and it was not really obvious to me that separate channels would be the preferred design. Not sure why I did not find the #270 issue when I was looking for info on thread safety.
