### ISSUE TITLE
Scaling multiple publisher subscriber configuration pubsub fanout

### ISSUE THREAD

**Issue by febytanzil** [streadway/amqp#347]
Hi, need some helps from you guys, trying to use fanout exchange as described pubsub pattern
https://www.rabbitmq.com/tutorials/tutorial-three-go.html
https://github.com/streadway/amqp/blob/master/_examples/pubsub/pubsub.go

#### Problem
1. Let say I have a subscriber function that listen to a specified exchange name
then I want that subscriber to be spawned > 1 go routines in my main.go for scaling
2. Let say I want a publisher function that can publish to any exchanges I want
#### Questions `#1`
- How to configure the Connection & Channel? Suppose I want 5 go routines, should I 
  - set 5 Connection w/ 1 Channel each
  - set 1 Connection w/ 5 Channel
- What is `ChannelMax` in Config struct used for? Will this give error if we try to open channel more that specified in that connection or is this a pool mechanism when we try to open a channel? Or something else?
- When do I need to close conn and or channel?
#### Questions `#2`
- Is it possible to do that with 1 Connection and or 1 Channel?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
See [Connections](https://www.rabbitmq.com/connections.html) and [Channels](https://www.rabbitmq.com/channels.html) guides. A single connection with 5 channels and 5 goroutines is optimal for a lot of cases. You can also use one channel but note that handling of recoverable errors happens on the per channel basis, so I'd say 5 channels may be a more resilient, easier to reason about design in that sense. Otherwise you definitely can get quite far with just one channel.
