### ISSUE TITLE
Exception (501) Reason: "read tcp 10.99.2.71:59205->10.99.2.71:5672: i/o timeout"

### ISSUE THREAD

**Issue by abusizhishen** [streadway/amqp#353]
when i run a consumer, the error occured `Exception (501) Reason: "read tcp 10.99.2.71:59205->10.99.2.71:5672: i/o timeout"`

what happened?

**Comment by bombsimon** [comment]
I think you need to provide some more information. The error you're showing happens when you're disconnected from the message bus. It can be reproduced simply by shutting down the rabbitmq server.

What makes this a surprise for you? Did you ensure there were no connection errors? Can you reproduce it? Were there other connections that didn't drop?

If you want a reliable system I think you should look into functionality to reconnect because these things happen.

**Comment by michaelklishin** [comment]
A TCP connection read timed out. This is not an indication of an issue in this client.

**Comment by ergoz** [comment]
same problem. rabbitmq works well without shutdowns, but this error in my worker happens sometimes. I uses default heartbeat (10s) and timeout (30s) like in this package

**Comment by michaelklishin** [comment]
@ergoz client connectivity is expected to fail at some point in a realistic system. This client or RabbitMQ or any other client cannot avoid that.

This client does not support [automatic recovery](http://www.rabbitmq.com/api-guide.html#recovery) by design but makes it reasonably easy to roll your own using the same strategy used e.g. by the Java client. See [this example](https://github.com/streadway/amqp/blob/master/_examples/pubsub/pubsub.go).

**Comment by michaelklishin** [comment]
Those who hit I/O timeouts upon initial connections (application start) should take a look at the [Troubleshooting Networking guide](https://www.rabbitmq.com/troubleshooting-networking.html) on rabbitmq.com.
