### ISSUE TITLE
I can't seem to get x-message-ttl to work in golang i've already installed the plugin

### ISSUE THREAD

**Issue by unisqu** [streadway/amqp#372]
I'm not sure if the installed delay schedule for rabbitmq is being used (i've installed the plugin but not sure how to check if it's running)

https://pastebin.com/u9yk6HGH

the code is above but i'm getting
2018/12/02 16:03:18 Failed to declare a queue: table field "x-message-ttl" value %!t(uint16=500) not supported

how do i get it to work in golang? pls help. thx

**Comment by lukebakken** [comment]
I see you cross-posted your question [here](https://github.com/rabbitmq/rabbitmq-server/issues/1786#issuecomment-443526322).

Rather than cross-post multiple repositories with a question, you should use the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list, or (as a last resort), a web site like Stack Overflow. The RabbitMQ team (who also helps maintain `streadway/amqp`) only uses GitHub issues for actual work - not questions.
