### ISSUE TITLE
Publishing to exchanges with wildcard routing key

### ISSUE THREAD

**Issue by samrreynolds4** [streadway/amqp#386]
Hello,

I'm publishing to an exchange using the routing key of `test.*` and then I'm making queues with the binding key of `test.1`. Everything works with no errors, but the queues don't receive any of the messages from the publishings.

Is it possible to do what I'm trying to do or is there a better method for doing what I'm trying to do, like a fanout exchange or something?

**Comment by michaelklishin** [comment]
Please post questions to the rabbitmq-users mailing list.

**Comment by michaelklishin** [comment]
An unroutable message is not an error condition in the protocol. Publishing to a non-existent exchange, however, is. Publish messages as mandatory and register a return handler if you want to detect unroutable ones.

I can only guess what you are trying to do. Sounds like you are trying to do topic-based routing which is [covered pretty well in the tutorials](https://www.rabbitmq.com/getstarted.html). With a topic exchange patterns are specified on the binding, not at the time of publishing. There's a tier 2 plugin that allows for "[reverse topic routing](https://github.com/rabbitmq/rabbitmq-rtopic-exchange)". It is not particularly popular but it does exist.

Not sure why a fanout would be a viable alternative since fanout exchange (also covered in the tutorials) route to every bound queue unconditionally.
