### ISSUE TITLE
go get github.com/streadway/amqp error

### ISSUE THREAD

**Issue by francis-bap** [streadway/amqp#398]
Trying to run `go get github.com/streadway/amqp`, I got the errors
`# github.com/streadway/amqp
src/github.com/streadway/amqp/types.go:204: syntax error: unexpected = in type declaration
src/github.com/streadway/amqp/types.go:208: syntax error: unexpected = in type declaration`
Did not notice this error last week.

**Comment by joaoluizn** [comment]
Same problem here.

**Comment by streadway** [comment]
This was from a recent merge of the internal package that uses type aliases in the public package.

Type aliases were introduced in go 1.9. And the minimum supported version of this package is 2 versions behind stable which is 1.10.

What version of Go are you using? `go version`

**Comment by streadway** [comment]
The change that uses type identity syntax from go 1.9 is reverted to think this through a bit more.

The two types that used this syntax are Table and Decimal. What's needed is assignability between the `amqp.Table/amqp.Decimal` and `proto.Table/proto.Decimal` types rather than identity.

These types could be used as fields in tables, and `amqp.Decimal` is only used as a table field. This could be addressed with a table data mapper between `amqp` and `proto` packages instead of type identity if we want pre go1.9 compatibility.

**Comment by francis-bap** [comment]
Thank you for the revert, it reworks now

**Comment by streadway** [comment]
@francis-bap can you let us know what go version you are using?

**Comment by francis-bap** [comment]
I was using go 1.8 on my container.

**Comment by michaelklishin** [comment]
Is Go 1.8 support a concern at this point? What about the medium term?

**Comment by michaelklishin** [comment]
@streadway should we revert the revert now that we know that the issue is on Go 1.8?

**Comment by streadway** [comment]
There are only 2 uses of the type assignment feature and there is a way to make that change compatible with earlier versions. I'm also doubtful of the value of the actual change, so there is no rush on reverting the revert.
