### ISSUE TITLE
Exception (501) Reason: "EOF" 

### ISSUE THREAD

**Issue by DRSchlaubi** [streadway/amqp#410]
I've tried to connect to my localhost amqp server using `amqp.Dial("amqp://guest:guest@localhost:5672/"` and got this error `Exception (501) Reason: "EOF"`.
I've also found #268 telling me I can only connect using `guest` user from localhost but that's exactly what I do. I've created another user but it stil gives me the same error.
Any ideas what I could do wrong?

**Comment by lukebakken** [comment]
I would start by [troubleshooting your network connection](https://www.rabbitmq.com/troubleshooting-networking.html). Running wireshark on port 5672 should provide an answer fairly quickly.

Is anything logged by RabbitMQ at the same time?

**Comment by michaelklishin** [comment]
Please follow the [methodology from this guide](https://www.rabbitmq.com/troubleshooting-networking.html) and consult [server logs](https://www.rabbitmq.com/logging.html#logged-events).

This client does not provide an automatic connection recovery feature by design so I'm not sure what else it could do when the socket returns an EOF. IIRC we have [a manual recovery example](https://github.com/streadway/amqp/tree/master/_examples).
